import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Inicio",
    link: "/",
  },
  {
    _id: 1002,
    title: "Tienda",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "Acerca",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contacto",
    link: "contact",
  },
  // {
  //   _id: 1005,
  //   title: "Journal",
  //   link: "/journal",
  // },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: imprimante1,
    productName: "Impresora",
    price: "35.00",
    color: "Blanco y Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Impresora",
  },
  {
    _id: "202",
    img: imprimante2,
    productName: "Impresora",
    price: "180.00",
    color: "Gris",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Impresora",
  },
  {
    _id: "203",
    img: imprimante4,
    productName: "Impresora",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Impresora",
  },
  {
    _id: "204",
    img: imprimante5,
    productName: "Impresora",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Impresora",
  },
  {
    _id: "205",
    img: imprimante6,
    productName: "Impresora",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Impresora",
  },
  {
    _id: "206",
    img: imprimante7,
    productName: "Impresora",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Impresora",
  },
  {
    _id: "207",
    img: imprimante8,
    productName: "Impresora",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Impresora",
  },
  {
    _id: "208",
    img: imprimante9,
    productName: "Impresora",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Impresora",
  },
  {
    _id: "209",
    img: encre1,
    productName: "Tinta",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Tinta",
  },
  {
    _id: "210",
    img: encre2,
    productName: "Tinta",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Tinta",
  },
  {
    _id: "211",
    img: encre3,
    productName: "Tinta",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Tinta",
  },
  {
    _id: "212",
    img: encre4,
    productName: "Tinta",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Tinta",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Cinta",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Cinta",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Cinta",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Cinta",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Cinta",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Cinta",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Cinta",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Cinta",
  },
  {
    _id: "217",
    img: bac1,
    productName: "Papelera",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Papelera",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Papelera",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Papelera",
  },
  {
    _id: "220",
    img: bac3,
    productName: "Papelera",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Papelera",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Papelera}",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Papelera",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "Impresora PANTUM CP2200DW",
    price: "35.00",
    color: "Blanco",
    badge: true,
    brand: "Pantum",
    des: " Impresora Laser PANTUM Colour - Funciones: Impresión - Tecnología de impresión: Laser - Tamaño de papel: A4 - Velocidad de impresión(Color/B/N): 24 ppm (A4) / 26 ppm (Carta) - Resolución de impresión: 600 x 600 dpi - Salida de papel: 100 páginas - Memoria: Dual core, 1 GHz - Impresión dúplex: Automática - Tiempo hasta la primera impresión: Menos de 11s - Conectores: USB 2.0 High Speed Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Inalámbrica 0 High Speed Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Wireless - Dimensiones: 411.2 x 394.1 x 243.7mm - Peso: 16.1 kg - Color: Blanco",
    cat: "Impresora",
    pdf: pdf1,
    ficheTech: [
      { label: "Tecnología ", value: "Láser monocromo electrofotográfico " },
      { label: "Velocidad de immpresión ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Ciclo de Trabajo MMensual Máximo", value: "15,000 pages " },
      {
        label: "Resolución recomendada para un volumen mensual de impresión(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "202",
    img: IMPRIMANTE_PANTUM_BM5100FDW,
    productName: "Impresora PANTUM CP2200DW",
    price: "35.00",
    color: "Blanco",
    badge: true,
    brand: "Pantum",
    des: " Impresora Laser PANTUM Colour - Funciones: Impresión - Tecnología de impresión: Laser - Tamaño de papel: A4 - Velocidad de impresión(Color/B/N): 24 ppm (A4) / 26 ppm (Carta) - Resolución de impresión: 600 x 600 dpi - Salida de papel: 100 páginas - Memoria: Dual core, 1 GHz - Impresión dúplex: Automática - Tiempo hasta la primera impresión: Menos de 11s - Conectores: USB 2.0 High Speed Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Inalámbrica 0 High Speed Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Wireless - Dimensiones: 411.2 x 394.1 x 243.7mm - Peso: 16.1 kg - Color: Blanco",
    cat: "Impresora",
    pdf: pdf1,
    ficheTech: [
      { label: "Tecnología ", value: "Láser monocromo electrofotográfico " },
      { label: "Velocidad de immpresión ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Ciclo de Trabajo MMensual Máximo", value: "15,000 pages " },
      {
        label: "Resolución recomendada para un volumen mensual de impresión(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },

  {
    _id: "203",
    img: IMPRIMANTE_PANTUM_BP5100DN,
    productName: "Impresora PANTUM CP2200DW",
    price: "35.00",
    color: "Blanco",
    badge: true,
    brand: "Pantum",
    des: " Impresora Laser PANTUM Colour - Funciones: Impresión - Tecnología de impresión: Laser - Tamaño de papel: A4 - Velocidad de impresión(Color/B/N): 24 ppm (A4) / 26 ppm (Carta) - Resolución de impresión: 600 x 600 dpi - Salida de papel: 100 páginas - Memoria: Dual core, 1 GHz - Impresión dúplex: Automática - Tiempo hasta la primera impresión: Menos de 11s - Conectores: USB 2.0 High Speed Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Inalámbrica 0 High Speed Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Wireless - Dimensiones: 411.2 x 394.1 x 243.7mm - Peso: 16.1 kg - Color: Blanco",
    cat: "Impresora",
    pdf: pdf1,
    ficheTech: [
      { label: "Tecnología ", value: "Láser monocromo electrofotográfico " },
      { label: "Velocidad de immpresión ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Ciclo de Trabajo MMensual Máximo", value: "15,000 pages " },
      {
        label: "Resolución recomendada para un volumen mensual de impresión(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "233",
    img: IMPRIMANTE_PANTUM_P2509,
    productName: "Impresora PANTUM P2509",
    price: "450",
    color: "Blanco",
    badge: true,
    brand: "Pantum",
    des: "Impresora láser PANTUM P2509 - Características de impresión - Capacidad de impresión Hasta :1600 páginas - Tamaños de papel: A4 - Tecnología de impresión láser monocromo - Velocidad de impresión en blanco y negro: Hasta 22 páginas por minuto en A4 - Resolución: 1200 ppp - Memoria: 128 MB - Conectividad: USB 2.0 - Dimensiones: 337 x 220 x 178 mm - Peso: 4,75 kg - Tóner recargable - Garantía: 1 año",
    cat: "Impresora",
    pdf: pdf1,
    ficheTech: [],
  },
  {
    _id: "220",
    img: bac3,
    productName: "Papelera",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Papelera",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Papelera",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Papelera",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Cinta",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Cinta",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Cinta",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Cinta",
  },
  {
    _id: "209",
    img: encre1,
    productName: "Tinta",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Tinta",
  },
  {
    _id: "210",
    img: encre2,
    productName: "Tinta",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Tinta",
  },

  {
    _id: "211",
    img: encre3,
    productName: "Tinta",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Tinta",
  },
  {
    _id: "212",
    img: encre4,
    productName: "Tinta",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Tinta",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Cinta",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Cinta",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Cinta",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Cinta",
  },

  {
    _id: "217",
    img: bac1,
    productName: "Papelera",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Papelera",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Papelera",
    price: "220.00",
    color: "Negro",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Papelera",
  },

//   // =================== imprimante hp =================

//   {
//     _id: "hp1",
//     img: hp1,
//     productName:
//       "IMPRIMANTE HP JET D'ENCRE HP SMART TANK 516 COULEUR MFP 3EN1 A4 WIFI",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Hp",
//     des: "Desc : Imprimante Jet D'encre HP SMART TANK 516 3en1 Couleur 3YW70A - Fonction: Impression, Copie, Numérisation - Technologie d'impression: jet d'encre - Vitesse d'impression Noir : Jusqu'à 22 ppm - Vitesse d’impression Couleur : Jusqu'à 16 ppm - Résolution d'impression Couleur : 1200x1200dpi - Format Papier : A4 - Capacité Papier : 100 feuilles -  Cycle d'utilisation (mensuel, A4) : Jusqu'à 1000pages - Connectivité: USB 2.0 haute vitesse, Wi-Fi, Bluetooth LE -  Dimensions: 447 x 373 x 158 mm - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "3YW70A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Ecran", value: "LCD" },
//       {
//         label: "Taille de L écran cm",
//         value: "Affichage LCD 7 segments + icône 5,08 cm (2 pouces)",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Technologie d impression", value: "Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Impression", value: "Couleur" },
//       { label: "formats", value: "A4" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 22 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 16 ppm" },
//       { label: "FAX", value: "Non" },
//       { label: "Mémoire", value: "256 Mo" },
//       {
//         label: "Qualité d impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 ppp",
//       },
//       {
//         label: "Qualité d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 ppp",
//       },
//       { label: "Résolution d impression Couleur", value: "1200x1200dpi" },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Connectivite", value: "USB 2.0, WiFi" },
//       { label: "Capacité papier", value: "100 feuilles" },
//       { label: "Cycle d utilisation Mensuel", value: "Jusqu'à 1000 pages" },
//       {
//         label: "Consommation électrique",
//         value:
//           "0,12 Watts (Arrêt manuel), 3,12 Watts (Prêt), 0,75 Watt (Veille) 5",
//       },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "Imprimante HP Smart Tank 516, Bouteilles d'encre: 3 x HP GT53XL (noir), 3 x HP GT52 (cyan, magenta et jaune), Notice de précaution pour l'encre; Fiche pour le ré-emballage et réglementaire RoH-EAC; Cordon d'alimentation, Guide d'installation; Notice PT",
//       },
//       { label: "Poids", value: "5,14 kg" },
//       { label: "Dimensions", value: "447 x 373 x 158 mm" },
//       { label: "Couleur", value: "Noir et Bleu" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },

//   {
//     _id: "hp2",
//     img: hp2,
//     productName: "IMPRIMANTE HP INK TANK WIRELESS 415 ALL-IN-ONE",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Hp",
//     des: "Desc : Imprimante Multifonction Jet d'encre 3 en 1 à réservoir intégré - Impression, numérisation, copie, sans fil - Résolution d'impression: Jusqu'à 4800 x 1200 dpi - Vitesse d'impression Couleur Jusqu'à 15 ppm -Vitesse d'impression N et B Jusqu'à 18 ppm - Résolution du scanner: 1200 x 1200 dpi - Format A4 - Interface USB - Bac d'alimentation de 60 feuilles - Dimensions: 525 x 310 x 158 mm - Garantie 1 an (+ Extension de Garantie 2 Ans ) + 5 Bouteilles",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [],
//   },

//   {
//     _id: "hp3",
//     img: hp3,
//     productName: "IMPRIMANTE HP INK TANK WIRELESS 415 ALL-IN-ONE",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Hp",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
//   // =================== imprimante ricoh =================
//   {
//     _id: "ricoh1",
//     img: ricoh1,
//     productName: "IMPRIMANTE RICOH P501",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },

//   {
//     _id: "ricoh2",
//     img: ricoh2,
//     productName: "IMPRIMANTE RICOH SP3710DN",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
//   {
//     _id: "ricoh3",
//     img: ricoh3,
//     productName: "IMPRIMANTE RICOH SP4520DN",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
//   {
//     _id: "ricoh4",
//     img: ricoh4,
//     productName: "IMPRIMANTE RICOH COULEUR LASER SPC840",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
//   {
//     _id: "ricoh5",
//     img: ricoh5,
//     productName: "IMPRIMANTE RICOH SP4510DN (407313)",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },

//   // =================== imprimante ricoh =================

//   {
//     _id: "espson1",
//     img: espson1,
//     productName: "IMPRIMANTE EPSON L3251 3EN1 A4 WIFI",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Epson",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },

//   {
//     _id: "espson2",
//     img: espson2,
//     productName: "IMPRIMANTE EPSON JET D'ENCRE L3156 COULEUR A4  WIFI",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Epson",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
];
